insert:
	psql -h localhost -d framebuff_db -U framebuff_user <create_user_table.sql
	psql -h localhost -d framebuff_db -U framebuff_user <create_video_table.sql
	psql -h localhost -d framebuff_db -U framebuff_user <insert_video_table.sql
	psql -h localhost -d framebuff_db -U framebuff_user <create_chat_table.sql
	psql -h localhost -d framebuff_db -U framebuff_user <user_movie_watch.sql